<template>
  <div class="AndroidLarge1">
    <img class="pknu_logo" :src="require('@/assets/white_logo.png')">
    <div class="Title">부경대학교<br/>모바일 도서관</div>

    <!-- 로그인 버튼 수정 -->
    <a :href="googleLoginUrl" class="google-login-button">
      <img class="google_login" :src="require('@/assets/sign_google.png')"/>
    </a>
  </div>
</template>

<script>
export default {
  computed: {
    googleLoginUrl() {
      // Replace with the actual URL generated by your backend for Google OAuth2
      return 'http://localhost:8082/oauth2/authorization/google';
    },
  },
  methods: {
    async checkLoginStatus() {
      // Simulate checking login status or use an appropriate method
      // You might want to make an API call to your backend here
      const isLoggedIn = true;  // Replace with actual logic

      if (isLoggedIn) {
        this.$router.push('/student/main');
      }
    },
  },
  mounted() {
    // Check the login status when the component is mounted
    this.checkLoginStatus();
  },
};
</script>




<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
.AndroidLarge1
{width: 360px;
height: 800px;
background: #173970;
}
.pknu_logo
{
  width: 185.31px;
  height: 250px;
  left: 87px;
  margin-top: 107px;
}
.Title
{
  width: 247px;
  height: 69px;
  margin-left: 57px;
  /* margin-top: 200px; */
  text-align: 'center';
  color: white;
  font-Size: 25px;
  /* fontFamily: 'Inter';
  fontWeight: '700';
  wordWrap: 'break-word'; */
}
</style>